credentials:
  usernames:
    demo_user:
      email: demo@demo.com
      name: Usuario de Prueba
      password: pbkdf2:sha256:260000$abc$abcde... # Contraseña encriptada
cookie:
  name: demo_cookie
  key: some_secret_key
  expiry_days: 30
