credentials:
  usernames:
    usuario1:
      email: usuario1@ejemplo.com
      name: Usuario Uno
      password: pbkdf2:sha256:260000$micontraseñaencriptada
cookie:
  name: autenticacion_conciencia
  key: secreto123
  expiry_days: 30
