DB_URL = "https://fploheqxhzpihgexlrkr.supabase.co"
api_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwbG9oZXF4aHpwaWhnZXhscmtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MjQyNzQsImV4cCI6MjA3MDUwMDI3NH0.D9ciX1Z1TcZWzl_BNLX8Q7TmPFpD_Tau5eV7opftpqs"
