DB_URL = "https://fploheqxhzpihgexlrkr.supabase.co"
DB_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwbG9oZXF4aHpwaWhnZXhscmtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MjQyNzQsImV4cCI6MjA3MDUwMDI3NH0.D9ciX1Z1TcZWzl_BNLX8Q7TmPFpD_Tau5eV7opftpqs"
api_key = "hTRHKEoz2gRAe68ILa7SqCq6T82lZn1muCV619EX"
COHERE_KEY = "hTRHKEoz2gRAe68ILa7SqCq6T82lZn1muCV619EX"
